import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='it'>
			<body className='md:container max-w-[95%] m-auto px-6 gap-32 lg:gap-40 flex flex-col pb-16'>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
