import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Navbar/Navbar';

import { Roboto } from 'next/font/google';

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	style: ['normal'],
	subsets: ['latin'],
	display: 'swap'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='it' className={roboto.className}>
			<body className='md:container m-auto px-6 gap-32 lg:gap-40 flex flex-col pb-16'>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
